source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'mysql'
gem 'sass-rails', '~> 4.0.2'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jquery-ui-themes'
gem 'jquery-multiselect-rails', :git => 'git://github.com/arojoal/jquery-multiselect-rails.git'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'youtube_it', github: 'kylejginavan/youtube_it'
gem 'rufus-scheduler'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'gon'
gem 'paperclip'
gem 'fitvidsjs_rails'
gem 'oauth2'
gem 'google-api-client'
gem 'unicorn'
gem 'kgio'
gem 'acts_as_indexed'

gem 'devise'

group :doc do
  gem 'sdoc', require: false
end
